"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
# move the rest of the prompt to the right 
right_format = """$cmd_duration$memory_usage$os$time$battery"""
# left prompt
format = """$all"""

[character]
#success_symbol = '[âžœ](bold green)'

[line_break]
disabled = true

[os]
disabled = false

[time]
disabled = false
format = '[$time]($style) '

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[cmd_duration]
format = '[$duration]($style) '

[memory_usage]
disabled = false
threshold = -1
format = '[${ram}]($style) '
